--- #YAML:1.0
name:                Task-Test-Run-AllPlugins
version:             0.0100
abstract:            Specifications for installing all the Test::Run
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::Run::CmdLine:            0
    Test::Run::CmdLine::Plugin::AlternateInterpreters: 0
    Test::Run::CmdLine::Plugin::ColorFileVerdicts: 0
    Test::Run::CmdLine::Plugin::ColorSummary: 0
    Test::Run::Core:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Shlomi Fish <shlomif@iglu.org.il>
